Repository alecluna/printworksapparel, pull requests merged in 2019-05, with the labels that each got.

#152 Specified file upload types
  src/request_quote.html
Labels: Story

#155 File upload fix
  src/request_quote.html
Labels: Hella High Priority

#153 Fix Gallery Images and Cloud Function
  lambda/getInstagramPics.js
  lambda/getYelpReviews.js
  src/css/fadein-animations.css
  src/css/gallery.css
  src/gallery.html
  src/javascript/requestImages.js
Labels: Small Fix, Work in Progress

#160 Testsuite
  AboutUs.png
  Gallery.png
  HomePage.png
  package-lock.json
  package.json
  src/testing/testAboutUs.js
  src/testing/testEstimate.js
  src/testing/testGallery.js
  src/testing/testHomePage.js
  src/testing/testServices.js
  yarn.lock
Labels: Done, Ready to Merge
